// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzllHPqpIasPeyB8n80H5djCHGcXu32Y',
    appId: '1:327536664016:web:f5463857ecde75bda96dd5',
    messagingSenderId: '327536664016',
    projectId: 'pos-motor-services',
    authDomain: 'pos-motor-services.firebaseapp.com',
    storageBucket: 'pos-motor-services.firebasestorage.app',
    measurementId: 'G-L7X8JQB9FL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDykcx5ND6CVLzkgvIUNr-77G2bTkSdQKU',
    appId: '1:327536664016:ios:b01cfa2173e4aba4a96dd5',
    messagingSenderId: '327536664016',
    projectId: 'pos-motor-services',
    storageBucket: 'pos-motor-services.firebasestorage.app',
    iosBundleId: 'com.example.d2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSzllHPqpIasPeyB8n80H5djCHGcXu32Y',
    appId: '1:327536664016:web:e378d8468b32322fa96dd5',
    messagingSenderId: '327536664016',
    projectId: 'pos-motor-services',
    authDomain: 'pos-motor-services.firebaseapp.com',
    storageBucket: 'pos-motor-services.firebasestorage.app',
    measurementId: 'G-QN3PZDE3JK',
  );
}
